### ISSUE TITLE
Is it possible to use bash envs instead of using ansible variables

### ISSUE THREAD

**Issue by kasir-barati** [moovs/ansible#1]
[Here you used Ansible variables instead of using `$USER`, why?](https://github.com/moovs/docker-with-ansible/blob/master/roles/docker/main.yml#L55-L59) Is not it possible to use old `$USER`?

I know we can do this: 
```yml
- name: Add current user to "docker" group
  shell: chmod -aG docker $USER
  tags: 
    - docker
    - chmod-current-user-group
```

But I am wondered if this is possible:
```
- name: Add remote "ubuntu" user to "docker" group
  user:
    name: "$USER"
    group: "docker"
    append: yes
  tags:
    - docker
    - add-current-user-to-docker-group
```
